GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "prengki putra utama",
    "email": "prengki@gmail.com",
    "gender": "male"
}

###
PATCH  http://localhost:5000/users/1 
Content-Type: application/json

{
    "name": "prengki putra utama S.kom",
    "email": "prengki@gmail.com",
    "gender": "male"
}

###
DELETE  http://localhost:5000/users/2 
